#if !defined(AFX_NWMP3PLAY_H__0B3FE6F6_2182_49BC_A3AB_2A37CB7F4863__INCLUDED_)
#define AFX_NWMP3PLAY_H__0B3FE6F6_2182_49BC_A3AB_2A37CB7F4863__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// Cnwmp3play wrapper class

class Cnwmp3play : public CWnd
{
protected:
	DECLARE_DYNCREATE(Cnwmp3play)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xaec11a5c, 0xde35, 0x4569, { 0xae, 0xfc, 0x6c, 0x51, 0x19, 0x98, 0x5d, 0x64 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChange_btpic(LPCTSTR lpszNewValue);
	void SetChange_dlgpic(LPCTSTR lpszNewValue);
	void SetMp3_filename(LPCTSTR lpszNewValue);
	void SetMp3_programname(LPCTSTR lpszNewValue);
	void SetMp3_vodipaddr(LPCTSTR lpszNewValue);
	void SetMp3_vodport(short nNewValue);
	void mp3_filemade();
	void mp3_netmode();
	void mp3_play();
	void mp3_pause();
	void mp3_stop();
	void change_skin();
	void mp3_filemode();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NWMP3PLAY_H__0B3FE6F6_2182_49BC_A3AB_2A37CB7F4863__INCLUDED_)
